apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 121gameon
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: 121gameon
resources:
- deployment.yaml
- service.yaml
images:
- name: grafana/grafana
  newTag: 6.1.6
