apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 121gameon
commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: 121gameon
resources:
- role.yaml
- service-account.yaml
- role-binding.yaml
- deployment.yaml
- service.yaml
images:
- name: prom/prometheus
  newTag: v2.3.2
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml
